// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOThCzRc1TJZ43RemjtskMgOIGc62fsHA',
    appId: '1:1078336729749:web:41e71ab7eed05d58e1619c',
    messagingSenderId: '1078336729749',
    projectId: 'messagingapp-c01b4',
    authDomain: 'messagingapp-c01b4.firebaseapp.com',
    storageBucket: 'messagingapp-c01b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_8wfSXG09WenDtsep2o23enMjDO57cwo',
    appId: '1:1078336729749:android:b603356490be0dc0e1619c',
    messagingSenderId: '1078336729749',
    projectId: 'messagingapp-c01b4',
    storageBucket: 'messagingapp-c01b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3CU9JSFaWLh78vDnO4MswS40y3QRTRrk',
    appId: '1:1078336729749:ios:f4c31ab5aced74ebe1619c',
    messagingSenderId: '1078336729749',
    projectId: 'messagingapp-c01b4',
    storageBucket: 'messagingapp-c01b4.appspot.com',
    iosClientId: '1078336729749-40kg5l142iimbclu294rmic9bkliv3c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3CU9JSFaWLh78vDnO4MswS40y3QRTRrk',
    appId: '1:1078336729749:ios:f62e159185ef8be1e1619c',
    messagingSenderId: '1078336729749',
    projectId: 'messagingapp-c01b4',
    storageBucket: 'messagingapp-c01b4.appspot.com',
    iosClientId: '1078336729749-0ukoptglto0dv7fh9hk1hbcri66brldi.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingapp.RunnerTests',
  );
}
